# Generated by Django 4.1.4 on 2022-12-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='test',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year_in_school',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
    ]
