# Generated by Django 4.1.4 on 2022-12-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=26)),
                ('dept_city', models.CharField(max_length=24)),
                ('dept_id', models.IntegerField(max_length=26)),
            ],
        ),
    ]
